services:
  web:
    build: .
    restart: always
    env_file:
      - .envs/prod.env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    # network는 컨테이너 간 통신할 때 쓰는 network 설정
    networks:
      - app_network
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:

volumes:
  static_volume:
  media_volume:
