# Generated by Django 5.1.5 on 2025-02-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("profile", "Profile Image"),
                            ("background", "Background Image"),
                            ("gallery", "Gallery Image"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image_url", models.URLField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "player_images",
            },
        ),
        migrations.CreateModel(
            name="TeamImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("profile", "Profile Image"),
                            ("background", "Background Image"),
                            ("gallery", "Gallery Image"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image_url", models.URLField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "team_images",
            },
        ),
        migrations.CreateModel(
            name="UserImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image_url", models.URLField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_image",
            },
        ),
    ]
