# Generated by Django 5.1.5 on 2025-02-19 21:39

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("realname", models.CharField(max_length=30)),
                ("nickname", models.CharField(max_length=30, unique=True)),
                ("gamename", models.CharField(max_length=50)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("top", "TOP"),
                            ("jungle", "JGL"),
                            ("mid", "MID"),
                            ("AD Carry", "AD"),
                            ("support", "SPT"),
                        ],
                        default=None,
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("debut_date", models.DateField()),
                ("social", models.JSONField(blank=True, default=dict, null=True)),
                ("agency", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("nationality", models.CharField(default="Korea", max_length=20)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="teams.team"
                    ),
                ),
            ],
            options={
                "db_table": "player",
            },
        ),
        migrations.CreateModel(
            name="PlayerSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("경기", "경기"), ("방송", "방송"), ("팬미팅", "팬미팅"), ("기타", "기타")],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("place", models.CharField(max_length=30, null=True)),
                ("title", models.CharField(default=None, max_length=50)),
                ("detail", models.CharField(blank=True, max_length=255)),
                ("player", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="players.player")),
            ],
            options={
                "db_table": "player_schedule",
            },
        ),
    ]
