# Generated by Django 5.1.5 on 2025-02-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[("top", "TOP"), ("jungle", "JGL"), ("mid", "MID"), ("bot", "AD"), ("support", "SPT")],
                default=None,
                max_length=10,
            ),
        ),
    ]
