# Generated by Django 5.1.5 on 2025-02-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_alter_player_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[("top", "TOP"), ("jungle", "JGL"), ("mid", "MID"), ("bot", "AD"), ("support", "SPT")],
                default=None,
                max_length=9,
            ),
        ),
    ]
