# Generated by Django 5.1.5 on 2025-02-19 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "0001_initial"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="playersubscription",
            name="user",
            field=models.ForeignKey(
                help_text="구독한 유저 식별자", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="teamsubscription",
            name="team",
            field=models.ForeignKey(
                help_text="구독한 팀 식별자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_subscriptions",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teamsubscription",
            name="user",
            field=models.ForeignKey(
                help_text="구독한 유저 식별자", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playersubscription",
            unique_together={("user_id", "player_id")},
        ),
        migrations.AlterUniqueTogether(
            name="teamsubscription",
            unique_together={("user_id", "team_id")},
        ),
    ]
