# Generated by Django 5.1.5 on 2025-02-13 18:21

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("name", models.CharField(help_text="팀 이름", max_length=30, unique=True)),
                (
                    "social",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="소셜 미디어 URL (insta, facebook, youtube, twitter)",
                        null=True,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "db_table": "team",
            },
        ),
        migrations.CreateModel(
            name="TeamSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(help_text="일정 카테고리", max_length=10)),
                ("start_date", models.DateTimeField(help_text="이벤트 시작 (end_date보다 작거나 같아야 함)")),
                ("end_date", models.DateTimeField(help_text="이벤트 종료 (start_date보다 크거나 같아야 함)")),
                ("place", models.CharField(help_text="장소", max_length=30)),
                ("title", models.CharField(help_text="제목", max_length=50)),
                ("detail", models.CharField(blank=True, help_text="내용", max_length=255, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        help_text="팀 식별자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_schedule",
            },
        ),
    ]
