name: Django CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_DATABASE }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ env.DB_USER }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: ${{ env.DB_USER }}
      DB_PASSWORD: ${{ env.DB_PASSWORD }}
      DB_DATABASE: ${{ env.DB_DATABASE }}

    steps:
        # 체크아웃 해야 최신 코드를 가져옴
      - name: Check out the codes
        uses: actions/checkout@v2

        # 파이썬 설치
      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.6'

        # 타임존 KST로 설정
      - name: Set timezone to KST
        run: |
          sudo rm /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime

      # Start PostgreSQL
      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql
          sudo -u postgres psql -c "ALTER USER ${{ env.DB_USER }} WITH PASSWORD '${{ env.DB_PASSWORD }}';"
          sudo -u postgres createdb ${{ env.DB_DATABASE }}

      - name: Install Poetry
        run: |
          curl -sSL curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-root
        # poetry 자기 자신을 설치하지 않음

      - name: Run black
        run: |
          poetry run black . --check
        # --check: 코드를 수정하지 않고 체크만 함

      - name: Run isort
        run: |
          poetry run isort . --check --diff
        # -diff: 달라진 점을 보여줌

      - name: Run Mypy
        run: |
          poetry run mypy .

#      - name: Setup tmate session 깃헙 액션 ssh로 디버깅
#        uses: mxschmitt/action-tmate@v3

      - name: Test python project
        run: |
          poetry run python manage.py test